booking/urls.py
from django.conf.urls import url

from . import views

app_name = "booking"
urlpatterns = [
    url(r'^join$', views.JoinView.as_view(), name='join'),
    url(r'^home$', views.HomeView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', views.BookingView.as_view(), name='view'),
    url(r'^new$', views.NewBookingView.as_view(), name='new'),
    url(r'^delete/(?P<pk>\d+)$', views.DeleteBookingView.as_view(),
        name='delete'),
]

padam/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from booking.forms import LoginForm

urlpatterns = [
    url(r'^account/login$', auth_views.login,
        {'authentication_form': LoginForm}, name='login'),
    url(r'^account/logout$',
        auth_views.logout, {'next_page': 'login'},
        name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^bookings/', include('booking.urls')),
]

booking/models.py
from django.contrib.auth.models import User
from django.db import models


class Car(models.Model):
    disponibility = models.BooleanField()

    def __str__(self):
        return str(self.id)


class Booking(models.Model):
    date = models.DateTimeField(
        auto_now_add=True, auto_now=False, verbose_name="Date de creation")
    reservation_date = models.DateTimeField(
        auto_now_add=False, auto_now=False, verbose_name="Date de réservation")
    car = models.OneToOneField(Car, related_name='car')
    user = models.ForeignKey(User, related_name='user')
    start_address = models.CharField(
        max_length=250, verbose_name="Adresse de départ")
    dest_address = models.CharField(
        max_length=250, verbose_name="Adresse de destination")
    state = models.BooleanField()
    duration = models.CharField(max_length=10)

    def __str__(self):
        return str(self.id)

booking/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from .models import Booking


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['start_address', 'dest_address']

    start_address = forms.CharField(max_length=250, label="Adresse de départ")
    dest_address = forms.CharField(
        max_length=250, label="Adresse de destination")


class JoinForm(forms.Form):
    surname = forms.CharField(max_length=50, label='Nom')
    firstname = forms.CharField(max_length=50, label='Prénom')
    email = forms.EmailField(label='Email')
    password = forms.CharField(
        max_length=15, widget=forms.PasswordInput, label='Mot de passe')


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Email",
        max_length=30,
        widget=forms.TextInput(
            attrs={'class': 'form-control',
                   'name': 'username'}))
    password = forms.CharField(
        label="Mot de passe",
        max_length=30,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                   'name': 'password'}))

booking/views.py
import logging
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DetailView, FormView, ListView,
                                  RedirectView)

from . import core
from .forms import BookingForm, JoinForm
from .models import Booking

logger = logging.getLogger(__name__)


class HomeView(ListView):
    template_name = 'booking/home.html'
    model = Booking

    def get_queryset(self):
        return Booking.objects.filter(user=self.request.user)


class BookingView(DetailView):
    template_name = 'booking/booking.html'
    model = Booking


class NewBookingView(CreateView):
    template_name = 'booking/new.html'
    model = Booking
    form_class = BookingForm
    success_url = reverse_lazy('booking:list')

    def form_valid(self, form):
        cars = core.get_cars()
        if len(cars) == 0:
            messages.add_message(self.request, messages.ERROR,
                                 "There is not any car available.")
            return redirect(self.get_success_url())

        try:
            duration = core.get_duration(form.cleaned_data['start_address'],
                                         form.cleaned_data['dest_address'])
        except core.GetDurationError:
            messages.add_message(self.request, messages.ERROR,
                                 "Could not find a way from {} to {}.".format(
                                    form.cleaned_data['start_address'],
                                    form.cleaned_data['dest_address']))
            return super().form_invalid(form)
        else:
            booking = form.save(commit=False)
            booked_car = cars[0]
            booking.duration = duration
            booking.reservation_date = datetime.now()
            booking.user = self.request.user
            booking.duration = duration
            booking.state = True
            booking.car = booked_car
            core.set_car_disponibility(booked_car.id, False)
            return super().form_valid(form)


class JoinView(FormView):
    template_name = 'booking/join.html'
    form_class = JoinForm

    def form_valid(self, form):
        django_user = User.objects.create(
            username=form.cleaned_data['email'],
            last_name=form.cleaned_data['surname'],
            first_name=form.cleaned_data['firstname'],
            email=form.cleaned_data['email'])

        django_user.set_password(form.cleaned_data['password'])
        django_user.save()
        return redirect(reverse('login'))


class DeleteBookingView(RedirectView):
    pattern_name = "booking:list"

    def get_redirect_url(self, *args, **kwargs):
        try:
            core.delete_booking(kwargs['pk'])
        except ObjectDoesNotExist:
            messages.add_message(self.request, messages.ERROR,
                                 "Could not delete non-existing booking.")
        del kwargs['pk']
        return super().get_redirect_url(*args, **kwargs)

booking/templates/booking/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>

	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">

	    <title>Padam Test Technique</title>
	</head>
	<body>
		<a href="{% url 'booking:list' %}" ><span>Home</span></a>
		<a href="{% url 'logout' %}" ><span>Logout</span></a>
		{% if messages %}
		<p>Some erros occured:</p>
		<ul class="messages">
			{% for message in messages %}
			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
			{% endfor %}
		</ul>
		{% endif %}
		{% block content %}
		{% endblock %}
	</body>
</html>

booking/templates/booking/booking.html
{% extends 'booking/base.html' %}

{% block content %}

<h1>Réservation réalisée le {{ object.reservation_date }}</h1>

<p>Adresse de départ : {{object.start_address }} </br> Adresse de destination : {{ object.dest_address }} </br>Durée estimée du trajet : {{ object.duration }} </br>ID car : {{ object.car }}</p>

{% endblock %}

booking/templates/booking/home.html
<style>
	table, th, td {
	    border: 1px solid black;
	    text-align: center;
	    margin: 20px;
	}
</style>

{% extends 'booking/base.html' %}

{% block content %}

<h1>Vos réservations sont :</h1>

<h3>
	<span>Créer une nouvelle réservation <a href="{% url 'booking:new' %}" >+</a></span>
</h3>

<table>
	<tr>
		<th>Voir plus</th>
		<th>Date de réservation</th>
		<th>Adresse de départ</th>
		<th>Adresse de destination</th>
		<th>Temps estimé</th>
		<th>Supprimer</th>
	</tr>
	{% for booking in object_list %}
	<tr>
		<td><a href="{% url 'booking:view' pk=booking.id %}" ><span>+</span></a></td>
		<td>{{ booking.reservation_date }}</td>
		<td>{{ booking.start_address }}</td>
		<td>{{ booking.dest_address }}</td>
		<td>{{ booking.duration }}</td>
		<td><a href="{% url 'booking:delete' pk=booking.id %}" ><span>x</span></a></td>
	</tr>
	{% endfor %}
</table>

{% endblock %}

booking/templates/booking/join.html
<a href="{% url 'login' %}" ><span>Login</span></a>

<form action="{% url "booking:join" %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

booking/templates/booking/new.html
{% extends 'booking/base.html' %}

{% block content %}
<form action="{% url "booking:new" %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}